FROM php:7.0-apache

# //This is used to install the extensions in the container so that 
# this service can connect with the database(backend)
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli


#Copy the file from host to the container.
COPY index.php /var/www/html

EXPOSE 80